### ISSUE TITLE
Use GH workflow syntax for container?

### ISSUE THREAD

**Issue by fingolfin** [gap-infra/actions#8]
Could we use [the official container support for Github Workflows](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-running-a-job-within-a-container) instead of calling `docker` manually? 

The reason why I think this *might* be useful (but I might be wrong) is that it should make it convenient to run multiple jobs using the container

Here is an example from the link above:
```yaml
jobs:
  my_job:
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
```
